id: dockerfile-user-root

info:
  name: Dockerfile Runs as root User
  author: geeknik
  severity: high
  description: Running containers as root increases breakout and privilege escalation impact.
  remediation: Set a non-root user in Dockerfile with USER and drop unnecessary privileges.
  reference:
    - https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
    - https://kubernetes.io/docs/concepts/security/pod-security-standards/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N
    cvss-score: 8.1
    cwe-id: CWE-250
  tags: file,docker,dockerfile,misconfig,hardening

file:
  - extensions:
      - all

    matchers:
      - type: regex
        regex:
          - '(?mi)^\s*USER\s+root\s*$'
