FROM php:7-apache

# Enable required Apache modules
RUN ln -s /etc/apache2/mods-available/headers.load /etc/apache2/mods-enabled/headers.load
RUN ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.load

# Install dependencies
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update && apt-get install -y --no-install-recommends \
    libpng-dev \
    libjpeg-dev \
    libmagickwand-dev \
    imagemagick \
    && pecl install \
    imagick \
    && docker-php-ext-enable \
    imagick \
    && docker-php-ext-configure \
    gd --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install \
    gd \
    && apt-get autoremove -y \
    libpng-dev \
    libjpeg-dev \
    libmagickwand-dev \
    && apt-get clean \
    && rm -rf \
    /tmp/* \
    /usr/share/doc/* \
    /var/cache/* \
    /var/lib/apt/lists/* \
    /var/tmp/*

# Copy application files
COPY server/php/ /var/www/html/

# Set permissions
RUN chmod -R 777 /var/www/html/files

EXPOSE 80
