id: apache-skywalking-horizon-ui-config

info:
  name: Apache SkyWalking Horizon UI - Config Exposure
  author: icarot
  severity: medium
  description: |
    Detects if path /api/auth/oidc/providers and /api/auth/health of SkyWalking Horizon UI server is exposed, getting authentication information.
  reference:
    - https://github.com/apache/skywalking-horizon-ui
  metadata:
    max-request: 2
    shodan-query: title:"SkyWalking Horizon UI"
    vendor: apache
    product: skywalking-horizon-ui
  tags: apache,skywalking-horizon-ui,config,exposure
http:
  - method: GET
    path:
      - "{{BaseURL}}/api/auth/oidc/providers"
      - "{{BaseURL}}/api/auth/health"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"backend":'
          - '"configured":'
          - '"ldap":'
          - '"breakGlass":'
          - '"passwordLogin":'
          - '"providers":'
        condition: or
      - type: status
        status:
          - 200
