id: dockerfile-hidden-disclosure

info:
  name: Dockerfile - Detect
  author: dhiyaneshDk
  severity: medium
  description: Dockerfile was detected.
  reference:
    - https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/dockerfile-hidden-disclosure.json
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 3
  tags: exposure,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/.dockerfile"
      - "{{BaseURL}}/.Dockerfile"
      - "{{BaseURL}}/Dockerfile"

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - '^(?:FROM(?:CACHE)?|RUN|ADD|WORKDIR|ENV|EXPOSE|\#)\s+[ -~]+'
        part: body

      - type: status
        status:
          - 200

      - type: word
        part: header
        words:
          - "text/html"
        negative: true
# digest: 4a0a004730450221009027aec894b72a9f993dcb7f6603bcb930c8cfb85985064f77402c431b3aa36f0220150a11dc6a452d3d673955474d449bfd93994eb977e12aa460a1239f29ae51f7:922c64590222798bb761d5b6d8e72950