id: dockerfile-hidden-disclosure

info:
  name: Dockerfile - Detect
  author: dhiyaneshDk
  severity: medium
  description: Dockerfile was detected.
  reference:
    - https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/dockerfile-hidden-disclosure.json
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 2
  tags: exposure,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/.dockerfile"
      - "{{BaseURL}}/.Dockerfile"
      - "{{BaseURL}}/Dockerfile"

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - '^(?:FROM(?:CACHE)?|RUN|ADD|WORKDIR|ENV|EXPOSE|\#)\s+[ -~]+'
        part: body

      - type: status
        status:
          - 200

      - type: word
        part: header
        words:
          - "text/html"
        negative: true
# digest: 4a0a00473045022100996bb3d5dbd3f9ea715206f973e79521b346b97d4514b0d361710ea4e489144c02203b0bb853de189dde12da3f4c702d4df157e0f1e66d5cacf5b3af793b817d21d0:922c64590222798bb761d5b6d8e72950