id: librechat-config-exposure

info:
  name: librechat - Config Exposure
  author: icarot
  severity: low
  description: |
    Detects if path /api/config of Librechat web application is exposed, getting internal information.
  classification:
    cpe: cpe:2.3:a:librechat:librechat:-:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: librechat
    product: librechat
    shodan-query: title:"librechat"
  tags: librechat,config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/api/config"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'LibreChat'
          - 'serverDomain'
          - 'registrationEnabled'
          - 'passwordResetEnabled'
        condition: and
      - type: status
        status:
          - 200
