id: librechat-config-exposure

info:
  name: librechat - Config Exposure
  author: icarot
  severity: low
  description: |
    Detected the `/api/config` endpoint of the LibreChat web application was publicly accessible, potentially exposing internal configuration details.
  classification:
    cpe: cpe:2.3:a:librechat:librechat:-:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: librechat
    product: librechat
    shodan-query: title:"librechat"
  tags: librechat,config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/api/config"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'LibreChat'
          - 'serverDomain'
          - 'registrationEnabled'
          - 'passwordResetEnabled'
        condition: and

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100f2270bd4291d977af75794138156fc1cb4983064f1038138df224b0d16293e2e022100c84e7a17f0e906f3455f1069a49716b9a75b62c3fbfea52998edc0d5bd4fac6c:922c64590222798bb761d5b6d8e72950