id: mercurial-hgignore

info:
  name: Mercurial Ignore - File Disclosure
  author: DhiyaneshDK,s4e-io
  severity: info
  description: Mercurial Ignore file disclosure was detected.
  reference:
    - https://swcarpentry.github.io/hg-novice/08-ignore/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
    cpe: cpe:2.3:a:mercurial:mercurial:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"hgignore"
    product: mercurial
    vendor: mercurial
  tags: exposure,hgignore,config,mercurial,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/.hgignore"

    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - 'len(body) > 50'
          - 'status_code == 200'
        condition: and

      - type: word
        words:
          - "MongoDB over HTTP on the native"
          - "application/javascript"
          - "application/x-javascript"
          - "application/json"
          - "application/xml"
          - "html"
          - "<!doctype"
          - "<script"
          - "<meta"
          - "image/"
          - "Response xmlns="
          - "text/xml"
          - "<?xml"
        part: response
        negative: true
        condition: or
# digest: 4b0a00483046022100f660db33d20398c87e4b7501ab6fbabbab565d62d3963774b330793d2d6bec1f022100a8a18beeeb94940da08be784da85e07d85f0bb59224a2bc823b80fe14cc26e06:922c64590222798bb761d5b6d8e72950