id: remote-spark-gateway-config

info:
  name: Remote Spark Gateway Configuration - Detect
  author: domwhewell-sage
  severity: medium
  description: Remote Spark Gateway config found via /gateway.conf.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
  tags: config,exposure,remote-spark,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/gateway.conf"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'html='
          - 'ssl='

      - type: status
        status:
          - 200
