id: litellm-swagger-detect

info:
  name: LiteLLM API - Swagger UI Detection
  author: rxerium
  severity: info
  description: |
    Detects exposed LiteLLM API Swagger UI interface. LiteLLM is a unified API for 100+ LLM providers (OpenAI, Azure, Anthropic, etc.).
  reference:
    - https://github.com/BerriAI/litellm
    - https://docs.litellm.ai/
  metadata:
    verified: true
    max-request: 1
    shodan-query: http.title:"LiteLLM API - Swagger UI"
  tags: tech,litellm,swagger,api,ai,llm

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "<title>LiteLLM API - Swagger UI"

      - type: status
        status:
          - 200
# digest: 4b0a004830460221008c9b870cf90fbc355996e303109c34f1feb4ae6d40f5c164d37a75a068174a7e0221008fca15870cc374fbc1f548055c1928113071e6eb8082a0fd3bd2717a03e59263:922c64590222798bb761d5b6d8e72950